### ISSUE TITLE
The css of this project is invalid

### ISSUE THREAD

**Issue by LittleSource** [xzMhehe/codingce-resume#1]
The css of this project is invalid because some libraries have been removed, welcome to fork my new work [react-resume](https://github.com/LittleSource/resume-react) to replace it.

**Comment by xzMhehe** [comment]
It has been repaired😁

**Comment by LittleSource** [comment]
no, you have to use my project and give me star ！！！

**Comment by LittleSource** [comment]
no, you have to use my project and give me star ！！！
